### ISSUE TITLE
OSX: Yosemite Error

### ISSUE THREAD

**Issue by DayOfThePenguin** [plasm-language/pyplasm#17]
I have both NumPy and SciPy installed, but still get this error.

117:build Colin$ cmake -GXcode ../
-- Setting PYPLASM_APPLE
-- PYTHON_EXECUTABLE: /usr/bin/python2.7
-- CMAKE_INSTALL_PREFIX: /Library/Python/2.7/site-packages/pyplasm
CMake Error at src/xgepy/FindNumPy.cmake:73 (math):
  math cannot parse the expression: "(1 \* 10000) + (8 \* 100) + 0rc1": syntax
  error, unexpected exp_NUMBER, expecting $end (30)
Call Stack (most recent call first):
  src/xgepy/CMakeLists.txt:27 (FIND_PACKAGE)

-- Using existing swig wrappers
-- Configuring incomplete, errors occurred!
See also "/Users/Colin/pyplasm/build/CMakeFiles/CMakeOutput.log".

**Comment by matteolefthanders** [comment]
I have the same issue...   Have you fixed it?

**Comment by DayOfThePenguin** [comment]
I haven't figured out a way to avoid it; it seems like it's something in the source and not a config error based on the error cmake is giving

**Comment by matteolefthanders** [comment]
Maybe cause se have yosemete

Inviato da HTC

----- Reply message -----
Da: "Colin Dablain" <notifications@github.com>
A: "plasm-language/pyplasm" <pyplasm@noreply.github.com>
Cc: "matteolefthanders" <matteomancini1990@gmail.com>
Oggetto: [pyplasm] OSX: Yosemite Error (#17)
Data: gio, mar 5, 2015 18:40

I haven't figured out a way to avoid it; it seems like it's something in the source and not a config error based on the error cmake is giving

&mdash;
